'use client';
import {useState,useRef,useEffect,useCallback} from 'react';
import {Flag,Play,ArrowUp,ArrowDown,Trophy,Timer,Gauge,ChevronRight,Users,MessageSquare,Volume2,VolumeX,LogIn,Settings,Send,Check,X,Medal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import RaceCanvas from '@/components/race-canvas';
import {Race,newRace,advance,botInput,TRACKS,TYRES,formatTime,lanesFor} from '@/lib/race';
import {firebaseAuth,googleProvider,signInWithPopup,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,onAuthStateChanged} from '@/lib/firebase-client';
const cities=['Global','București','Cluj','Iași','Timișoara','Constanța'];
const API_ORIGIN='https://michelin-race-paddock.winner-onlin-1903.chatgpt.site';
async function api(action:string,data:Record<string,unknown>={}){const token=await firebaseAuth.currentUser?.getIdToken();const r=await fetch(`${API_ORIGIN}/api/game`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({action,...data})});const b:any=await r.json();if(!r.ok)throw new Error(b.error||'Conexiunea a fost întreruptă.');return b;}
const initial=()=>({...newRace('ring',[{id:'you',name:'Tu',lane:0,tyre:'medium'}]),status:'ready' as const});
export default function Paddock(){
 const [tab,setTab]=useState('race'),[track,setTrack]=useState('ring'),[tyre,setTyre]=useState('medium'),[lane,setLane]=useState(0),[mode,setMode]=useState('solo');
 const [race,setRace]=useState<Race>(initial),state=useRef<Race>(initial()),input=useRef(0),net=useRef<string|null>(null),modeRef=useRef('solo'),meRef=useRef<any>(null),syncAt=useRef(0),pausedRef=useRef(false);
 const [lobby,setLobby]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[room,setRoom]=useState<string|null>(null),[paused,setPaused]=useState(false),[pauseUntil,setPauseUntil]=useState(0);
 const [profile,setProfile]=useState(false),[draft,setDraft]=useState({name:'',country:'România',avatar:'P',tyre:'medium'}),[channel,setChannel]=useState('Global'),[messages,setMessages]=useState<any[]>([]),[chatText,setChatText]=useState(''),[chatError,setChatError]=useState(''),[rank,setRank]=useState('general'),[recordTrack,setRecordTrack]=useState('ring');
 const [pilotView,setPilotView]=useState<any>(null);
 const [createOpen,setCreateOpen]=useState(false),[tForm,setTForm]=useState({name:'',track:'ring',starts:'',max:'8',rules:'8 tururi · Dueluri eliminatorii · +3 / −3 puncte'}),[seasonName,setSeasonName]=useState(''),[muted,setMuted]=useState(true);
 const [authOpen,setAuthOpen]=useState(false),[authMode,setAuthMode]=useState<'login'|'register'>('login'),[authForm,setAuthForm]=useState({email:'',password:''}),[authError,setAuthError]=useState('');
 const [authUser,setAuthUser]=useState(firebaseAuth.currentUser),[authReady,setAuthReady]=useState(false);
 const audio=useRef<{ctx:AudioContext;osc:OscillatorNode;gain:GainNode}|null>(null),mutedRef=useRef(true);
 const refresh=useCallback(async()=>{try{const token=await firebaseAuth.currentUser?.getIdToken();const r=await fetch(`${API_ORIGIN}/api/game`,{headers:token?{Authorization:`Bearer ${token}`}:{}});const b:any=await r.json();if(!r.ok)throw new Error(b.error);setLobby(b);meRef.current=b.me;setError('');if(b.activeRoom&&!net.current){net.current=b.activeRoom;setRoom(b.activeRoom);setTab('race');}}catch(e:any){setError(e.message||'Serviciul online nu răspunde.');}},[]);
 useEffect(()=>onAuthStateChanged(firebaseAuth,u=>{setAuthUser(u);setAuthReady(true);void refresh();}),[refresh]);
 useEffect(()=>{void refresh();const timer=setInterval(refresh,3500);return()=>clearInterval(timer);},[refresh]);
 const run=async(fn:()=>Promise<any>,success?:string)=>{setBusy(true);setNotice('');try{await fn();if(success)setNotice(success);await refresh();return true;}catch(e:any){setNotice(e.message);return false;}finally{setBusy(false);}};
 useEffect(()=>{let frame=0,last=0,draw=0;function tick(now:number){const dt=Math.min((now-last)/1000||0,.05);last=now;const r=state.current,c=r.cars.find(c=>c.id===meRef.current?.id)||r.cars[0];
  if(c)c.input=input.current;if(!net.current){if(modeRef.current==='bot'&&r.cars[1])r.cars[1].input=botInput(r,r.cars[1]);advance(r,dt);}else if(!pausedRef.current&&performance.now()-syncAt.current<650){advance(r,dt);}
  if(audio.current){audio.current.osc.frequency.setTargetAtTime(38+(c?.speed||0)*.7,audio.current.ctx.currentTime,.08);audio.current.gain.gain.setTargetAtTime(!mutedRef.current&&r.status==='racing'&&!pausedRef.current? .024:0,audio.current.ctx.currentTime,.08);}
  if(now-draw>33){setRace(structuredClone(r));draw=now;}frame=requestAnimationFrame(tick);
 }frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);void audio.current?.ctx.close();};},[]);
 useEffect(()=>{const held=new Set<string>();const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement)return;if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();e.type==='keyup'?held.delete(e.key):held.add(e.key);input.current=held.has('ArrowDown')?-1:held.has('ArrowUp')?1:0;}};const clear=()=>{held.clear();input.current=0;};window.addEventListener('keydown',key);window.addEventListener('keyup',key);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('keyup',key);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);};},[]);
 useEffect(()=>{if(!room)return;let alive=true,timer:ReturnType<typeof setTimeout>;async function poll(){try{const d=await api('tick',{id:room,input:input.current});if(!alive)return;state.current=d.race;syncAt.current=performance.now();pausedRef.current=d.paused;setPaused(d.paused);setPauseUntil(d.pauseUntil);setTrack(d.race.track);setRace(structuredClone(d.race));if(d.race.status==='finished'){net.current=null;setRoom(null);setPaused(false);pausedRef.current=false;await refresh();return;}}catch(e:any){if(!alive)return;pausedRef.current=true;setPaused(true);setNotice(e.message);}if(alive)timer=setTimeout(poll,180);}void poll();return()=>{alive=false;clearTimeout(timer);};},[room,refresh]);
 const loadChat=useCallback(async()=>{if(!meRef.current)return;try{const token=await firebaseAuth.currentUser?.getIdToken();const r=await fetch(`${API_ORIGIN}/api/game?channel=`+encodeURIComponent(channel),{headers:token?{Authorization:`Bearer ${token}`}:{}}),b:any=await r.json();if(!r.ok)throw new Error(b.error);setMessages(b.messages);setChatError('');}catch(e:any){setChatError(e.message);}},[channel]);
 useEffect(()=>{setMessages([]);void loadChat();const t=setInterval(loadChat,3500);return()=>clearInterval(t);},[loadChat,lobby?.me?.id]);
 function start(kind=mode){if(net.current)return;input.current=0;modeRef.current=kind;const p=[{id:'you',name:lobby?.me?.name||'Tu',lane,tyre}];if(kind==='bot')p.push({id:'bot',name:'Pilot de antrenament',lane:1-lane,tyre:'medium'});state.current=newRace(track,p);setRace(structuredClone(state.current));setTab('race');setNotice('');}
 function choose(id:string){if(net.current||['racing','countdown'].includes(state.current.status))return;setTrack(id);state.current={...newRace(id,[{id:'you',name:'Tu',lane,tyre}]),status:'ready'};setRace(structuredClone(state.current));}
 function sound(){const value=!muted;setMuted(value);mutedRef.current=value;if(!value&&!audio.current){const ctx=new AudioContext(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sawtooth';gain.gain.value=0;osc.connect(gain);gain.connect(ctx.destination);osc.start();audio.current={ctx,osc,gain};}if(!value)void audio.current?.ctx.resume();}
 function openProfile(){if(!lobby?.me)return;setDraft({name:lobby.me.name,country:lobby.me.country,avatar:lobby.me.avatar,tyre:lobby.me.tyre});setProfile(true);}
 const startRef=useRef(start);startRef.current=start;
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{void Promise.resolve(context.registerTool({name:'read_race_status',description:'Read current circuit, elapsed time, laps, and cars.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>structuredClone(state.current)},{signal:life.signal})).catch(()=>{});void Promise.resolve(context.registerTool({name:'start_practice_race',description:'Start an unranked solo practice race on the selected circuit. Refuses during an active race.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:(value:any)=>{if(!value||Object.keys(value).length||net.current||['racing','countdown'].includes(state.current.status))throw new Error('Cannot start practice now.');startRef.current('solo');return {status:state.current.status,track:state.current.track};}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[]);
 const me=lobby?.me,c=race.cars.find(c=>c.id===me?.id)||race.cars[0],lap=Math.min(race.target,Math.floor(c.distance/lanesFor(race.track)[c.lane].length)+1),active=['racing','countdown'].includes(race.status)||!!room;
 const online=(lobby?.players||[]).filter((p:any)=>Date.now()-p.seen<15000&&p.id!==me?.id);
 const ordered=[...race.cars].sort((a,b)=>b.distance/lanesFor(race.track)[b.lane].length-a.distance/lanesFor(race.track)[a.lane].length),isDuel=race.cars.some(c=>c.id!=='you'&&c.id!=='bot');
 const ranking=rank==='season'?lobby?.standings:rank==='tournament'?[...(lobby?.players||[])].map((p:any)=>({...p,points:(lobby?.tournaments||[]).filter((t:any)=>t.winner===p.id).length})).sort((a,b)=>b.points-a.points):lobby?.players;
 const invites=lobby?.invitations||[];
 return <main className="app"><header className="topbar"><a href="/" className="brand"><span className="brand-mark"><Flag size={23}/></span><span><strong>MICHELIN</strong><small>RACE CHALLENGE</small></span></a><span className="edition">THE PADDOCK <span>/</span> RECONSTRUIT</span><div className="header-right">{authUser?<><span className="status-dot"/>{me?.name||authUser.displayName||authUser.email}<button className="avatar" disabled={!me} onClick={openProfile} aria-label="Editează profilul">{me?.avatar||(authUser.email?.[0]||'P').toUpperCase()}</button><button className="signin" onClick={()=>void signOut(firebaseAuth)}>Ieșire</button></>:authReady?<button className="signin" onClick={()=>setAuthOpen(true)}><LogIn size={16}/>Conectare</button>:<span className="signin">Se verifică sesiunea…</span>}</div></header>
 <div className="workspace"><div className="page-heading"><div><div className="eyebrow">BUN VENIT ÎN PADDOCK</div><h1>Fiecare viraj contează<span>.</span></h1></div><span className="season-label"><Flag size={15}/>{lobby?.season?.name||'SEZONUL 01'}</span></div>
 {error&&<div className="online-notice" role="status">{error} <button onClick={refresh}>Reîncearcă</button></div>}
 {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Închide notificarea"><X size={15}/></button></div>}
 <Tabs value={tab} onValueChange={setTab}><TabsList className="main-tabs" variant="line"><TabsTrigger value="race"><Flag/>Paddock</TabsTrigger><TabsTrigger value="tracks"><Gauge/>Circuite</TabsTrigger><TabsTrigger value="ranking"><Trophy/>Clasamente</TabsTrigger><TabsTrigger value="tournaments"><Medal/>Turnee</TabsTrigger><TabsTrigger value="rules"><Timer/>Regulament</TabsTrigger>{!!me?.admin&&<TabsTrigger value="admin"><Settings/>Administrare</TabsTrigger>}</TabsList>
 <TabsContent value="race">
 {invites.map((v:any)=><div className="invite" key={v.id}><div><span className="eyebrow">{v.tournament?'DUEL DE TURNEU':'PROVOCARE 1 VS 1'}</span><strong>{v.host===me?.id?'Îl aștepți pe '+v.guestName:v.hostName+' te provoacă'} <small>· {TRACKS.find(t=>t.id===v.data.race.track)?.name}</small></strong></div>{v.guest===me?.id?<div className="invite-actions"><select aria-label="Alege culoarul" value={lane} onChange={e=>setLane(Number(e.target.value))}><option value={0}>Culoar galben</option><option value={1}>Culoar albastru</option></select><Button disabled={busy||active} className="yellow-button" onClick={()=>run(async()=>{const d=await api('accept',{id:v.id,lane,tyre});net.current=d.id;setRoom(d.id);setTab('race');})}><Check size={16}/>Acceptă</Button>{!v.tournament&&<Button variant="ghost" disabled={busy} onClick={()=>run(()=>api('decline',{id:v.id}))}>Refuză</Button>}</div>:!v.tournament&&<Button variant="outline" disabled={busy} onClick={()=>run(()=>api('decline',{id:v.id}))}>Anulează</Button>}</div>)}
 <div className="game-grid"><section className="track-panel"><div className="panel-top"><div><span className="eyebrow">{isDuel?'DUEL CLASAT · 1 VS 1':modeRef.current==='bot'?'ANTRENAMENT CU ADVERSAR':'ANTRENAMENT LIBER'}</span><h2>{TRACKS.find(t=>t.id===race.track)?.name}</h2></div><span className="tag">{race.target} TURURI <span>•</span> SLOT-CAR</span></div>
 <div className="canvas-wrap"><RaceCanvas race={race}/>{race.status==='ready'&&<div className="race-overlay"><span className="eyebrow">GĂSEȘTE RITMUL PERFECT</span><h2>Pregătit de start?</h2><p>Accelerează pe drepte. Frânează înainte de viraje.</p><Button onClick={()=>start()} className="yellow-button"><Play size={16}/>Intră pe circuit</Button></div>}
 {race.status==='countdown'&&!paused&&<div className="countdown">{Math.ceil(race.countdown)}<small>PREGĂTEȘTE-TE</small></div>}
 {race.status==='finished'&&<div className="race-overlay"><Trophy className="gold"/><h2>{race.winner===c.id?'Ai trecut primul!':race.winner?'Cursă încheiată':'Duel anulat'}</h2><p>{race.reason||formatTime(race.time)+' · Cel mai bun tur '+formatTime(c.bestLap)}</p>{isDuel&&race.winner&&<strong className="gold">{race.winner===me?.id?'+3':'−3'} puncte</strong>}<Button onClick={()=>start()} className="yellow-button">Înapoi la antrenament</Button></div>}
 {paused&&<div className="race-overlay"><h2>Reconectare…</h2><p>Cursa este suspendată pentru ambii piloți.</p><strong className="gold">{pauseUntil?Math.max(0,Math.ceil((pauseUntil-Date.now())/1000)):'10'} secunde</strong></div>}
 {race.extra&&race.status==='racing'&&<div className="extra-lap">Egalitate · Tur suplimentar</div>}
 <button className="sound-button" onClick={sound} aria-label={muted?'Activează sunetul':'Oprește sunetul'}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button></div>
 <div className="telemetry"><div><small>VITEZĂ</small><strong>{Math.round(c.speed)} <em>km/h</em></strong><div className="speed-bar"><i style={{width:`${c.speed/270*100}%`}}/></div></div><div><small>TUR</small><strong>{String(lap).padStart(2,'0')} <em>/ {race.target}</em></strong></div><div><small>TIMP TOTAL</small><strong>{formatTime(race.time)}</strong></div><div><small>CEL MAI BUN TUR</small><strong>{formatTime(c.bestLap)}</strong></div></div>
 {race.cars.length>1&&<div className="race-positions">{ordered.map((car,i)=><div key={car.id}><b style={{color:car.lane===0?'#ffdc54':'#5ac7ff'}}>{i+1}</b><span>{car.name}</span><strong>{i===0?'LIDER':'+'+Math.max(0,((ordered[0].distance/lanesFor(race.track)[ordered[0].lane].length-car.distance/lanesFor(race.track)[car.lane].length)*lanesFor(race.track)[car.lane].length/Math.max(40,car.speed))).toFixed(2)+'s*'}</strong><small>Ultimul tur {formatTime(car.lastLap)}</small></div>)}<small>* Diferență estimată din progresul pe circuit.</small></div>}
 <div className="controls"><span><kbd>↑</kbd> Accelerație <kbd>↓</kbd> Frână</span><span>{c.crashes?c.crashes+' ieșiri de pe pistă':'Eliberează accelerația pentru a încetini gradual.'}</span>{!isDuel&&active&&<button onClick={()=>{state.current.status='ready';input.current=0;}}>Oprește</button>}</div>
 <div className="touch-controls"><Button onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.current=-1;}} onPointerUp={()=>input.current=0} onPointerCancel={()=>input.current=0}><ArrowDown/>Frână</Button><Button className="yellow-button" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.current=1;}} onPointerUp={()=>input.current=0} onPointerCancel={()=>input.current=0}><ArrowUp/>Accelerație</Button></div></section>
 <aside className="right-stack"><section className="panel setup"><div className="section-title"><h2>Pregătirea cursei</h2><span>01</span></div><label htmlFor="track">CIRCUIT</label><select id="track" disabled={active} value={track} onChange={e=>choose(e.target.value)}>{TRACKS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><label>PNEURI</label><div className="tyre-options">{TYRES.map(t=><button key={t.id} disabled={active} className={tyre===t.id?'tyre selected':'tyre'} onClick={()=>setTyre(t.id)}><span className="tyre-ring" style={{borderColor:t.color}}>{t.name[0]}</span><strong>{t.name}</strong><small>{t.label}</small></button>)}</div><p className="muted">{TYRES.find(t=>t.id===tyre)?.description}</p>
 <div className="setup-bottom"><select aria-label="Mod de antrenament" disabled={active} value={mode} onChange={e=>setMode(e.target.value)}><option value="solo">Antrenament solo</option><option value="bot">Cu adversar de antrenament</option></select><select aria-label="Culoar antrenament" disabled={active} value={lane} onChange={e=>setLane(Number(e.target.value))}><option value={0}>Culoar galben</option><option value={1}>Culoar albastru</option></select></div>
 <Button className="yellow-button full" disabled={active} onClick={()=>start()}><Play size={16}/>Începe antrenamentul<ChevronRight size={16}/></Button><small className="footnote">Fără puncte · Recorduri doar în dueluri</small></section>
 <section className="panel online-panel"><div className="section-title"><h2><Users size={17}/>Piloți online</h2><span className="count-pill">{online.length}</span></div>{!me?<p className="muted">Conectează-te pentru a provoca alți piloți.<br/><a className="text-link" href="/signin-with-chatgpt?return_to=/" target="_top">Conectare →</a></p>:online.length===0?<div className="empty-small"><span className="status-dot"/>Ești primul pe circuit.<p>Un alt pilot conectat va apărea aici.</p></div>:online.slice(0,8).map((p:any)=><div className="player-row" key={p.id}><span className="mini-avatar">{p.avatar}</span><div><strong>{p.name}</strong><small>{p.points} puncte · {p.tyre}</small></div><Button variant="outline" size="sm" disabled={active||busy} onClick={()=>run(()=>api('challenge',{target:p.id,track,tyre}),'Provocarea a fost trimisă.')}>Provoacă</Button></div>)}</section></aside></div>
 <div className="community-grid"><section className="panel leaderboard"><div className="section-title"><h2><Trophy size={17}/>Clasament general</h2><button className="text-link" onClick={()=>setTab('ranking')}>Vezi tot →</button></div>{!(lobby?.players?.length)?<p className="muted">Primele dueluri vor scrie clasamentul.</p>:(lobby.players.slice(0,5)).map((p:any,i:number)=><div className="leader-row" key={p.id}><span className={i===0?'rank gold':'rank'}>{String(i+1).padStart(2,'0')}</span><span className="status-dot" style={{background:Date.now()-p.seen<15000?'#54d9a0':'#d76b70'}}/><button className="pilot-name" onClick={()=>setPilotView(p)}>{p.name}</button><span>{p.points}<small> PCT</small></span></div>)}</section>
 <section className="panel chat"><div className="section-title"><h2><MessageSquare size={17}/>Paddock chat</h2><select aria-label="Canal de chat" value={channel} onChange={e=>setChannel(e.target.value)}>{cities.map(c=><option key={c}>{c}</option>)}{(lobby?.memberships||[]).map((id:string)=><option key={id} value={'tournament:'+id}>{lobby.tournaments.find((t:any)=>t.id===id)?.name||'Turneu'}</option>)}{(lobby?.players||[]).filter((p:any)=>p.id!==me?.id).map((p:any)=><option key={p.id} value={'dm:'+p.id}>Privat · {p.name}</option>)}</select></div><div className="chat-messages" aria-live="polite">{!me?<p className="muted">Conectează-te ca să intri în conversație.</p>:messages.length?messages.map(m=><div className="chat-line" key={m.id}><strong>{m.name}</strong><p>{m.body}</p><time>{new Date(m.created).toLocaleTimeString('ro-RO',{hour:'2-digit',minute:'2-digit'})}</time></div>):<p className="muted">Circuit liber. Spune primul salut.</p>}</div>{chatError&&<p className="inline-error">{chatError}</p>}<form onSubmit={async e=>{e.preventDefault();if(!chatText.trim()||busy)return;const body=chatText;const ok=await run(()=>api('message',{channel,body}));if(ok){setChatText('');await loadChat();}}}><input aria-label="Mesaj" placeholder={channel.startsWith('dm:')?'Scrie un mesaj privat…':'Scrie în paddock…'} maxLength={500} value={chatText} disabled={!me} onChange={e=>setChatText(e.target.value)}/><Button type="submit" aria-label="Trimite mesajul" disabled={!me||busy||!chatText.trim()}><Send size={17}/></Button></form></section>
 <section className="panel events"><div className="section-title"><h2><Flag size={17}/>Evenimente</h2></div>{(lobby?.tournaments||[]).filter((t:any)=>['open','running'].includes(t.status)).slice(0,2).map((t:any)=><button className="event-card" key={t.id} onClick={()=>setTab('tournaments')}><small>{new Date(t.starts).toLocaleDateString('ro-RO',{day:'2-digit',month:'short'})}</small><strong>{t.name}</strong><span>{t.count} piloți · {t.status==='running'?'În desfășurare':'Înscrieri deschise'}</span></button>)}{!(lobby?.tournaments||[]).some((t:any)=>['open','running'].includes(t.status))&&<div className="empty-small"><Flag size={25}/><h3>Următorul start oficial</h3><p>Evenimentele programate de administrator vor apărea aici.</p></div>}</section></div></TabsContent>
 <TabsContent value="tracks"><div className="track-catalog">{TRACKS.map((t,i)=><button key={t.id} disabled={active} className="panel track-choice" onClick={()=>{choose(t.id);setTab('race');}}><span className="eyebrow">CIRCUIT {String(i+1).padStart(2,'0')}</span><h2>{t.name}</h2><RaceCanvas race={{...newRace(t.id,[]),status:'ready'}}/><p>{t.place} · {t.level}</p><span>{track===t.id?'Circuit selectat':'Selectează circuitul'} →</span></button>)}</div></TabsContent>
 <TabsContent value="ranking"><div className="ranking-grid"><section className="panel ranking-panel"><div className="section-title"><h2>Grila de elită</h2><select value={rank} onChange={e=>setRank(e.target.value)} aria-label="Tip clasament"><option value="general">General</option><option value="season">{lobby?.season?.name||'Sezon'}</option><option value="tournament">Titluri de turneu</option></select></div><div className="table-scroll"><table><thead><tr><th>LOC</th><th>PILOT</th><th>{rank==='tournament'?'TITLURI':'PUNCTE'}</th><th>VICTORII</th><th>ÎNFRÂNGERI</th><th>RATĂ VICTORII</th></tr></thead><tbody>{(ranking||[]).map((p:any,i:number)=>{const total=lobby.players.find((a:any)=>a.id===p.id)||p;return <tr key={p.id}><td className={i===0?'gold':''}>{String(i+1).padStart(2,'0')}</td><td><span className="status-dot" style={{background:Date.now()-p.seen<15000?'#54d9a0':'#d76b70'}}/> <button className="pilot-name" onClick={()=>setPilotView(total)}>{p.name}</button><small className="country">{total.country}</small></td><td className="gold">{p.points}</td><td>{total.wins}</td><td>{total.losses}</td><td>{total.wins+total.losses?Math.round(total.wins/(total.wins+total.losses)*100):0}%</td></tr>;})}</tbody></table></div>{!ranking?.length&&<p className="muted">Niciun pilot în clasament încă.</p>}</section>
 <section className="panel records"><div className="section-title"><h2><Timer size={18}/>Recorduri</h2></div><select aria-label="Circuit recorduri" value={recordTrack} onChange={e=>setRecordTrack(e.target.value)}>{TRACKS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>{['lap','total'].map(key=>{const record=[...(lobby?.records||[])].filter((r:any)=>r.track===recordTrack&&r[key]).sort((a,b)=>a[key]-b[key])[0];return <div className="record-block" key={key}><small>{key==='lap'?'CEL MAI RAPID TUR':'CEL MAI RAPID DUEL'}</small><strong>{record?formatTime(record[key]):'—'}</strong><span>{record?.name||'Record de stabilit'}</span></div>;})}<p className="muted">Doar timpi validați în dueluri. Ieșirile de pe pistă nu invalidează turul.</p><div className="record-block"><small>CELE MAI MULTE VICTORII</small><strong>{[...(lobby?.players||[])].sort((a,b)=>b.wins-a.wins)[0]?.wins||0}</strong><span>{[...(lobby?.players||[])].sort((a,b)=>b.wins-a.wins)[0]?.name||'—'}</span></div></section></div>
 <section className="panel recent"><h2>Ultimele dueluri</h2>{!(lobby?.recent?.length)?<p className="muted">Rezultatele vor apărea după primul duel.</p>:lobby.recent.map((r:any)=><div className="history-row" key={r.id}><Trophy size={16} className="gold"/><strong>{r.winnerName}</strong><span>a câștigat împotriva lui {r.loserName}</span><small>{TRACKS.find(t=>t.id===r.track)?.name}</small><b className="gold">+3</b></div>)}</section></TabsContent>
 <TabsContent value="tournaments"><div className="section-title"><h2>Turnee oficiale</h2>{!!me?.admin&&<Button className="yellow-button" onClick={()=>setCreateOpen(true)}>Creează turneu</Button>}</div><div className="tournament-grid">{(lobby?.tournaments||[]).map((t:any)=><section className="panel tournament-card" key={t.id}><span className="eyebrow">{({open:'ÎNSCRIERI DESCHISE',running:'ÎN DESFĂȘURARE',finished:'ÎNCHEIAT',cancelled:'ANULAT'} as any)[t.status]}</span><h2>{t.name}</h2><p>{TRACKS.find(x=>x.id===t.track)?.name} · {new Date(t.starts).toLocaleString('ro-RO')}</p><div className="tournament-numbers"><strong>{t.count}<small> / {t.max} piloți</small></strong><span>1 VS 1</span></div><p className="muted">{t.rules}</p>{t.status==='open'&&<Button className="yellow-button full" disabled={!me||busy||lobby.memberships.includes(t.id)||t.count>=t.max} onClick={()=>run(()=>api('join',{id:t.id}),'Ești înscris în turneu.')}>{lobby.memberships.includes(t.id)?'Înscris':t.count>=t.max?'Locuri ocupate':'JOIN TOURNAMENT'}</Button>}{t.winner&&<p className="gold"><Trophy size={17}/> Câștigător: {lobby.players.find((p:any)=>p.id===t.winner)?.name}</p>}{[...(t.data.history||[]),...(t.data.pairs?.length?[{round:t.data.round,pairs:t.data.pairs}]:[])].map((round:any)=><div className="bracket" key={round.round}><small>RUNDA {round.round}</small>{round.pairs.map((p:any,i:number)=><div key={i}><span>{lobby.players.find((a:any)=>a.id===p.a)?.name}</span><b>vs</b><span>{p.b?lobby.players.find((a:any)=>a.id===p.b)?.name:'Calificare directă'}</span>{p.winner&&<Check size={15} className="gold"/>}</div>)}</div>)}</section>)}</div>{!lobby?.tournaments?.length&&<section className="panel empty-state"><Medal size={40}/><h2>Următorul campion poți fi tu.</h2><p>Administratorul va programa primul turneu. Până atunci, exersează traseele.</p><Button onClick={()=>setTab('race')} className="yellow-button">Înapoi pe circuit</Button></section>}</TabsContent>
 <TabsContent value="rules"><section className="panel rules"><h2>Un control simplu. O cursă de precizie.</h2><p><b>Comenzi.</b> ↑ accelerează gradual; ↓ frânează mai puternic. Eliberarea accelerației produce încetinire naturală. Direcția este automată. Pe telefon, ține apăsate butoanele de sub circuit.</p><p><b>Aderență.</b> Viteza și curbura traseului determină ieșirea de pe pistă, fără zaruri sau probabilități. Revii automat după o secundă, cu viteză zero, din punctul ieșirii. La Crossroads, mașinile se pot lovi în intersecție: ambele revin după o secundă.</p><p><b>Duel.</b> Cel care provoacă alege circuitul; cel provocat alege culoarul. Fiecare pilot își alege pneurile. Semaforul numără 3 secunde, apoi începe cursa de 8 tururi. O egalitate la maximum 0,01 secunde adaugă un tur fără oprire; regula se repetă dacă este necesar.</p><p><b>Puncte și recorduri.</b> +3 puncte pentru victorie, −3 pentru înfrângere; punctajul poate fi negativ. Sezonul are clasament separat. Recordurile provin doar din dueluri, iar ieșirile de pe pistă nu invalidează turul. Antrenamentele și adversarul automat nu acordă puncte.</p><p><b>Conexiune.</b> Lipsa semnalului suspendă ambele mașini. Ai 10 secunde de la ultimul semnal pentru reconectare; cursa reia starea salvată pe server. Dacă nu revii, pierzi. Dacă ambii piloți dispar, duelul se anulează.</p><p><b>Turnee.</b> Doar administratorii creează evenimente. La ora programată, sistemul formează duelurile în timpul verificării paddock-ului. Numărul impar de participanți produce o calificare directă. Invitațiile de turneu au două minute pentru acceptare; neprezentarea este departajată după ultima prezență online. Sunt necesari minimum doi înscriși.</p><p><b>Pneuri.</b> Soft favorizează aderența, Medium este echilibrat, Hard favorizează viteza. Toate sunt disponibile, fără uzură în această versiune.</p></section></TabsContent>
 {!!me?.admin&&<TabsContent value="admin"><div className="admin-grid"><section className="panel rules"><h2>Controlul competiției</h2><p>Contul tău administrează turneele și sezoanele. Crearea evenimentelor este verificată pe server.</p><Button className="yellow-button" onClick={()=>setCreateOpen(true)}>Programează un turneu</Button></section><section className="panel rules"><h2>Încheie sezonul curent</h2><p>Clasamentul general se păstrează. Liderul primește un titlu de sezon; noul clasament pornește de la zero.</p><form onSubmit={e=>{e.preventDefault();void run(()=>api('season',{name:seasonName}),'Noul sezon a început.');}}><input aria-label="Numele sezonului nou" required minLength={3} maxLength={40} placeholder="Numele sezonului nou" value={seasonName} onChange={e=>setSeasonName(e.target.value)}/><Button disabled={busy||active} type="submit" className="yellow-button">Încheie și începe sezonul nou</Button></form></section></div></TabsContent>}</Tabs>
 <footer>MICHELIN RACE CHALLENGE <span>Proiect independent · Reconstrucție comunitară</span></footer></div>
 <Dialog open={authOpen} onOpenChange={setAuthOpen}><DialogContent><DialogHeader><DialogTitle>{authMode==='login'?'Conectare în paddock':'Creează cont'}</DialogTitle><DialogDescription>Folosește e-mail și parolă sau continuă cu Google.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e=>{e.preventDefault();setAuthError('');try{if(authMode==='login')await signInWithEmailAndPassword(firebaseAuth,authForm.email,authForm.password);else await createUserWithEmailAndPassword(firebaseAuth,authForm.email,authForm.password);setAuthOpen(false);await refresh();}catch(err:any){setAuthError(err?.code==='auth/email-already-in-use'?'Există deja un cont cu acest e-mail.':err?.code==='auth/invalid-credential'?'E-mail sau parolă incorectă.':'Autentificarea nu a reușit. Verifică datele.');}}}><label>E-mail<input required type="email" autoComplete="email" value={authForm.email} onChange={e=>setAuthForm({...authForm,email:e.target.value})}/></label><label>Parolă<input required minLength={6} type="password" autoComplete={authMode==='login'?'current-password':'new-password'} value={authForm.password} onChange={e=>setAuthForm({...authForm,password:e.target.value})}/></label>{authError&&<p className="inline-error">{authError}</p>}<Button type="submit" className="yellow-button full">{authMode==='login'?'Conectare':'Creează cont'}</Button><Button type="button" variant="outline" onClick={()=>void signInWithPopup(firebaseAuth,googleProvider).then(()=>{setAuthOpen(false);void refresh();}).catch(()=>setAuthError('Conectarea Google nu a reușit.'))}>Continuă cu Google</Button><button type="button" className="text-link" onClick={()=>{setAuthMode(authMode==='login'?'register':'login');setAuthError('');}}>{authMode==='login'?'Nu ai cont? Creează unul':'Ai deja cont? Conectează-te'}</button></form></DialogContent></Dialog>
 <Dialog open={!!pilotView} onOpenChange={open=>{if(!open)setPilotView(null);}}><DialogContent><DialogHeader><DialogTitle>{pilotView?.name}</DialogTitle><DialogDescription>{pilotView?.country} · {pilotView&&Date.now()-pilotView.seen<15000?'Online':'Offline'}</DialogDescription></DialogHeader><div className="profile-stats"><span><b>{pilotView?.points||0}</b>Puncte</span><span><b>{pilotView?.wins||0}</b>Victorii</span><span><b>{pilotView?.losses||0}</b>Înfrângeri</span><span><b>{pilotView?.titles||0}</b>Titluri sezon</span></div><p className="muted">Poziția #{(lobby?.players||[]).findIndex((p:any)=>p.id===pilotView?.id)+1} · Rată victorii {pilotView?.wins+pilotView?.losses?Math.round(pilotView.wins/(pilotView.wins+pilotView.losses)*100):0}%</p><div className="pilot-records">{TRACKS.map(t=>{const r=(lobby?.records||[]).filter((r:any)=>r.player===pilotView?.id&&r.track===t.id).sort((a:any,b:any)=>a.lap-b.lap)[0];return <div key={t.id}><span>{t.name}</span><strong>{r?formatTime(r.lap):'—'}</strong></div>;})}</div></DialogContent></Dialog>
 <Dialog open={profile} onOpenChange={setProfile}><DialogContent><DialogHeader><DialogTitle>Profilul tău de pilot</DialogTitle><DialogDescription>Numele și statisticile tale sunt vizibile în paddock.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e=>{e.preventDefault();if(await run(()=>api('profile',draft),'Profil salvat.')){setProfile(false);setTyre(draft.tyre);}}}><label>Nume pilot<input required minLength={2} maxLength={24} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Țară<input required minLength={2} maxLength={40} value={draft.country} onChange={e=>setDraft({...draft,country:e.target.value})}/></label><label>Inițiale avatar<input required maxLength={3} value={draft.avatar} onChange={e=>setDraft({...draft,avatar:e.target.value})}/></label><label>Pneuri preferate<select value={draft.tyre} onChange={e=>setDraft({...draft,tyre:e.target.value})}>{TYRES.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="profile-stats"><span><b>{me?.points||0}</b>Puncte</span><span><b>{me?.wins||0}</b>Victorii</span><span><b>{me?.losses||0}</b>Înfrângeri</span><span><b>{me?.titles||0}</b>Titluri sezon</span></div><Button type="submit" disabled={busy} className="yellow-button full">Salvează profilul</Button></form></DialogContent></Dialog>
 <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent><DialogHeader><DialogTitle>Programează un turneu</DialogTitle><DialogDescription>Participanții se vor înscrie din pagina Turnee.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e=>{e.preventDefault();if(await run(()=>api('tournament',{...tForm,starts:new Date(tForm.starts).getTime(),max:Number(tForm.max)}),'Turneul a fost programat.'))setCreateOpen(false);}}><label>Nume<input required minLength={3} maxLength={60} value={tForm.name} onChange={e=>setTForm({...tForm,name:e.target.value})}/></label><label>Circuit<select value={tForm.track} onChange={e=>setTForm({...tForm,track:e.target.value})}>{TRACKS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Data și ora locală<input required type="datetime-local" value={tForm.starts} onChange={e=>setTForm({...tForm,starts:e.target.value})}/></label><label>Locuri<select value={tForm.max} onChange={e=>setTForm({...tForm,max:e.target.value})}>{[2,4,8,16,32].map(n=><option key={n}>{n}</option>)}</select></label><label>Reguli<textarea required maxLength={500} value={tForm.rules} onChange={e=>setTForm({...tForm,rules:e.target.value})}/></label><Button type="submit" disabled={busy} className="yellow-button full">Creează turneul</Button></form></DialogContent></Dialog>
 </main>;
}



