import {advance,newRace,TRACKS,TYRES,type Race} from './race';
type DB=any;
type RoomData={race:Race;seen:number[];tick:number;paused:boolean;pauseUntil:number;season:string};
export const CITIES=['Global','București','Cluj','Iași','Timișoara','Constanța'];
function fail(message:string,status=400):never{throw Object.assign(new Error(message),{status});}
function text(v:unknown,min=1,max=40){if(typeof v!=='string'||v.trim().length<min||v.trim().length>max)fail(`Textul trebuie să aibă între ${min} și ${max} de caractere.`);return (v as string).trim();}
function validTrack(v:unknown){if(!TRACKS.some(t=>t.id===v))fail('Circuit invalid.');return v as string;}
function validTyre(v:unknown){if(!TYRES.some(t=>t.id===v))fail('Pneuri invalide.');return v as string;}
export class GameService{
 constructor(private db:DB,private uid:string|null,private now=Date.now()){}
 q(sql:string,...args:unknown[]){return this.db.prepare(sql).bind(...args);}
 async one(sql:string,...args:unknown[]):Promise<any>{return this.q(sql,...args).first();}
 async all(sql:string,...args:unknown[]):Promise<any[]>{return (await this.q(sql,...args).all()).results||[];}
 async me(){if(!this.uid)fail('Conectează-te pentru dueluri, chat și clasamente.',401);let p=await this.one('SELECT * FROM players WHERE id=?',this.uid);if(!p){await this.q("INSERT OR IGNORE INTO players (id,name,seen,created,admin) SELECT ?,?,?,?,CASE WHEN COUNT(*)=0 THEN 1 ELSE 0 END FROM players",this.uid,'Pilot_'+this.uid!.slice(-5),this.now,this.now).run();p=await this.one('SELECT * FROM players WHERE id=?',this.uid);}if(this.now-p.seen>2000)await this.q('UPDATE players SET seen=? WHERE id=?',this.now,this.uid).run();return p;}
 async season(){let s=await this.one('SELECT * FROM seasons WHERE active=1 ORDER BY created DESC LIMIT 1');if(!s){await this.q("INSERT OR IGNORE INTO seasons(id,name,active,created) VALUES('season-1','Sezonul 01',1,?)",this.now).run();s=await this.one('SELECT * FROM seasons WHERE active=1 ORDER BY created DESC LIMIT 1');}return s;}
 async lobby(){const me=this.uid?await this.me():null,season=await this.season();await this.advanceTournaments();const players=await this.all('SELECT * FROM players ORDER BY points DESC,wins DESC,name LIMIT 200');const standings=await this.all('SELECT p.id,p.name,p.avatar,p.seen,COALESCE(SUM(CASE WHEN r.winner=p.id THEN 3 WHEN r.loser=p.id THEN -3 ELSE 0 END),0) as points FROM players p LEFT JOIN results r ON (r.winner=p.id OR r.loser=p.id) AND r.season=? GROUP BY p.id ORDER BY points DESC,p.name',season.id);const invitations=me?await this.all("SELECT r.*,p.name as hostName,g.name as guestName FROM rooms r JOIN players p ON p.id=r.host JOIN players g ON g.id=r.guest WHERE (r.host=? OR r.guest=?) AND r.status='invited' AND (r.created>? OR r.tournament IS NOT NULL) ORDER BY r.created DESC LIMIT 20",me.id,me.id,this.now-120000):[];const activeRoom=me?await this.one('SELECT room FROM locks WHERE player=?',me.id):null;const records=await this.all('SELECT r.*,p.name FROM records r JOIN players p ON p.id=r.player ORDER BY lap ASC LIMIT 300');const tournaments=await this.all('SELECT t.*,(SELECT COUNT(*) FROM entrants e WHERE e.tournament=t.id) as count FROM tournaments t ORDER BY starts DESC LIMIT 30');const memberships=me?await this.all('SELECT tournament FROM entrants WHERE player=?',me.id):[];const recent=await this.all('SELECT r.*,w.name as winnerName,l.name as loserName FROM results r JOIN players w ON w.id=r.winner JOIN players l ON l.id=r.loser ORDER BY created DESC LIMIT 12');return {me,season,players,standings,invitations:invitations.map(r=>({...r,data:JSON.parse(r.data)})),activeRoom:activeRoom?.room||null,records,tournaments:tournaments.map(t=>({...t,data:JSON.parse(t.data)})),memberships:memberships.map(x=>x.tournament),recent,now:this.now};}
 async profile(data:any){const me=await this.me();await this.q('UPDATE players SET name=?,country=?,avatar=?,tyre=? WHERE id=?',text(data.name,2,24),text(data.country,2,40),text(data.avatar,1,3),validTyre(data.tyre),me.id).run();return {ok:true};}
 async challenge(data:any){const me=await this.me(),target=await this.one('SELECT * FROM players WHERE id=?',data.target);if(!target||target.id===me.id)fail('Alege un alt pilot.');if(this.now-target.seen>15000)fail('Pilotul nu mai este online.');if(await this.one('SELECT player FROM locks WHERE player IN (?,?)',me.id,target.id))fail('Unul dintre piloți este deja într-o cursă.',409);const recent=await this.one('SELECT COUNT(*) as n FROM rooms WHERE host=? AND created>?',me.id,this.now-60000);if(recent.n>=8)fail('Așteaptă puțin înainte de o nouă provocare.',429);const id=crypto.randomUUID(),s=await this.season(),r:RoomData={race:newRace(validTrack(data.track),[{id:me.id,name:me.name,lane:0,tyre:validTyre(data.tyre)},{id:target.id,name:target.name,lane:1,tyre:target.tyre}]),seen:[this.now,this.now],tick:this.now,paused:false,pauseUntil:0,season:s.id};await this.q("INSERT INTO rooms(id,host,guest,status,data,created) VALUES(?,?,?,'invited',?,?)",id,me.id,target.id,JSON.stringify(r),this.now).run();return {id};}
 async roomFor(id:string){const r=await this.one('SELECT * FROM rooms WHERE id=?',id);if(!r)fail('Duelul nu mai există.',404);if(!this.uid||![r.host,r.guest].includes(this.uid))fail('Acest duel aparține altor piloți.',403);return r;}
 async accept(data:any){const me=await this.me(),row=await this.roomFor(data.id);if(row.guest!==me.id||row.status!=='invited')fail('Provocarea nu mai poate fi acceptată.',409);if(!row.tournament&&this.now-row.created>120000)fail('Provocarea a expirat.');if(data.lane!==0&&data.lane!==1)fail('Culoar invalid.');const d:RoomData=JSON.parse(row.data);d.race.cars[1].lane=data.lane;d.race.cars[0].lane=1-data.lane;d.race.cars[1].tyre=validTyre(data.tyre);d.seen=[this.now,this.now];d.tick=this.now;d.season=(await this.season()).id;try{await this.db.batch([this.q('INSERT INTO locks(player,room) VALUES(?,?)',row.host,row.id),this.q('INSERT INTO locks(player,room) VALUES(?,?)',row.guest,row.id),this.q("UPDATE rooms SET status='active',data=?,rev=rev+1 WHERE id=? AND status='invited'",JSON.stringify(d),row.id)]);}catch{fail('Unul dintre piloți a intrat deja într-un duel.',409);}return {id:row.id};}
 async decline(data:any){await this.me();const row=await this.roomFor(data.id);if(row.status!=='invited'||row.tournament)fail('Provocarea nu poate fi anulată.');await this.q("UPDATE rooms SET status='cancelled' WHERE id=? AND status='invited'",row.id).run();return {ok:true};}
 async tick(data:any){await this.me();if(![-1,0,1].includes(data.input))fail('Comandă invalidă.');for(let attempt=0;attempt<6;attempt++){const row=await this.roomFor(data.id),d:RoomData=JSON.parse(row.data),i=row.host===this.uid?0:1;
  if(row.status==='finished'){await this.settle(row,d);return {...d,id:row.id};}if(row.status!=='active')fail('Duelul nu a început.',409);
  const missing=d.seen.map((t,index)=>({index,age:this.now-t})).filter(x=>x.age>1200);
  if(missing.length){d.paused=true;d.pauseUntil=Math.min(...missing.map(x=>d.seen[x.index]+10000));if(this.now>d.pauseUntil){const present=d.seen.map((t,index)=>({index,age:this.now-t})).filter(x=>x.age<=10000);d.race.winner=present.length===1?d.race.cars[present[0].index].id:null;d.race.status='finished';d.race.reason=d.race.winner?'Victorie prin deconectare':'Ambii piloți s-au deconectat. Duel anulat.';}}
  if(d.race.status!=='finished'){if(!d.paused){const end=Math.min(this.now,Math.min(...d.seen)+250);advance(d.race,Math.max(0,Math.min(1.5,(end-d.tick)/1000)));d.tick=Math.max(d.tick,end);}d.seen[i]=this.now;d.race.cars[i].input=data.input;if(d.paused&&d.seen.every(t=>this.now-t<1200)){d.paused=false;d.pauseUntil=0;d.tick=this.now;for(const c of d.race.cars)c.input=0;}}
  const status=d.race.status==='finished'?'finished':'active',updated=await this.q('UPDATE rooms SET data=?,rev=rev+1,status=? WHERE id=? AND rev=?',JSON.stringify(d),status,row.id,row.rev).run();if(updated.meta.changes){if(status==='finished')await this.settle({...row,status},d);return {...d,id:row.id};}
 }fail('Sincronizarea se reîncearcă.',409);}
 async settle(row:any,d:RoomData){const r=d.race;if(!r.winner){await this.q('DELETE FROM locks WHERE room=?',row.id).run();return;}const winner=r.winner,loser=r.cars.find(c=>c.id!==winner)!.id,token=crypto.randomUUID(),qs=[this.q('INSERT OR IGNORE INTO results(id,token,winner,loser,track,time,season,tournament,created) VALUES(?,?,?,?,?,?,?,?,?)',row.id,token,winner,loser,r.track,r.time,d.season,row.tournament||null,this.now),this.q('UPDATE players SET points=points+3,wins=wins+1 WHERE id=? AND EXISTS(SELECT 1 FROM results WHERE id=? AND token=?)',winner,row.id,token),this.q('UPDATE players SET points=points-3,losses=losses+1 WHERE id=? AND EXISTS(SELECT 1 FROM results WHERE id=? AND token=?)',loser,row.id,token),this.q('DELETE FROM locks WHERE room=?',row.id)];for(const c of r.cars)if(c.bestLap>0&&!r.reason)qs.push(this.q('INSERT OR IGNORE INTO records(id,player,track,lap,total,room) VALUES(?,?,?,?,?,?)',row.id+':'+c.id,c.id,r.track,c.bestLap,c.finished,row.id));await this.db.batch(qs);}
 async channel(raw:unknown){const me=await this.me(),ch=text(raw,1,180);if(CITIES.includes(ch))return ch;if(ch.startsWith('dm:')){const target=ch.slice(3);if(target===me.id||!await this.one('SELECT id FROM players WHERE id=?',target))fail('Destinatar invalid.');return 'private:'+JSON.stringify([me.id,target].sort());}if(ch.startsWith('tournament:')){const tid=ch.slice(11);if(me.admin||await this.one('SELECT id FROM entrants WHERE tournament=? AND player=?',tid,me.id))return ch;}fail('Nu ai acces la acest canal.',403);}
 async chat(channel:unknown){const ch=await this.channel(channel);const messages=await this.all('SELECT m.id,m.body,m.created,m.sender,p.name,p.avatar FROM messages m JOIN players p ON p.id=m.sender WHERE channel=? ORDER BY m.created DESC LIMIT 60',ch);return {messages:messages.reverse()};}
 async message(data:any){const ch=await this.channel(data.channel);const last=await this.one('SELECT created FROM messages WHERE sender=? ORDER BY created DESC LIMIT 1',this.uid);if(last&&this.now-last.created<800)fail('Așteaptă o clipă înainte de următorul mesaj.',429);await this.q('INSERT INTO messages(id,channel,sender,body,created) VALUES(?,?,?,?,?)',crypto.randomUUID(),ch,this.uid,text(data.body,1,500),this.now).run();return {ok:true};}
 async admin(){const p=await this.me();if(!p.admin)fail('Acțiune rezervată administratorului.',403);return p;}
 async createTournament(data:any){await this.admin();const starts=Number(data.starts),max=Number(data.max);if(!Number.isFinite(starts)||starts<this.now||![2,4,8,16,32].includes(max))fail('Alege o dată viitoare și 2–32 de participanți.');const id=crypto.randomUUID();await this.q("INSERT INTO tournaments(id,name,track,starts,max,rules,status,data,created) VALUES(?,?,?,?,?,?,'open','{}',?)",id,text(data.name,3,60),validTrack(data.track),starts,max,text(data.rules,3,500),this.now).run();return {id};}
 async join(data:any){const me=await this.me();const t=await this.one('SELECT * FROM tournaments WHERE id=?',data.id);if(!t||t.status!=='open'||t.starts<=this.now)fail('Înscrierile s-au încheiat.');await this.q('INSERT OR IGNORE INTO entrants(id,tournament,player) SELECT ?,?,? WHERE (SELECT COUNT(*) FROM entrants WHERE tournament=?)<?',t.id+':'+me.id,t.id,me.id,t.id,t.max).run();if(!await this.one('SELECT id FROM entrants WHERE id=?',t.id+':'+me.id))fail('Turneul este complet.');return {ok:true};}
 async newSeason(data:any){await this.admin();const s=await this.season(),name=text(data.name,3,40);const ongoing=await this.one("SELECT id FROM rooms WHERE status='active' LIMIT 1");if(ongoing)fail('Așteaptă încheierea duelurilor active.');const winner=await this.one('SELECT id,SUM(points) AS score FROM (SELECT winner AS id,3 AS points FROM results WHERE season=? UNION ALL SELECT loser AS id,-3 AS points FROM results WHERE season=?) GROUP BY id ORDER BY score DESC,id LIMIT 1',s.id,s.id);const newId=crypto.randomUUID();const changed=await this.db.batch([this.q('INSERT INTO seasons(id,name,active,created) SELECT ?,?,1,? WHERE EXISTS(SELECT 1 FROM seasons WHERE id=? AND active=1) AND NOT EXISTS(SELECT 1 FROM rooms WHERE status=\'active\')',newId,name,this.now,s.id),this.q('UPDATE players SET titles=titles+1 WHERE id=? AND EXISTS(SELECT 1 FROM seasons WHERE id=?)',winner?.id||'',newId),this.q('UPDATE seasons SET active=0,winner=? WHERE id=? AND EXISTS(SELECT 1 FROM seasons WHERE id=?)',winner?.id||null,s.id,newId)]);if(!changed[0].meta.changes)fail('Sezonul s-a schimbat sau a început un duel. Reîncearcă.',409);return {ok:true};}
 async advanceTournaments(){const ts=await this.all("SELECT * FROM tournaments WHERE status='running' OR (status='open' AND starts<=?)",this.now);for(const t of ts){let data:any=JSON.parse(t.data),ids:string[]=[];const qs:any[]=[];
  if(t.status==='open'){ids=(await this.all('SELECT player FROM entrants WHERE tournament=? ORDER BY id',t.id)).map(e=>e.player);if(ids.length<2){await this.q("UPDATE tournaments SET status='cancelled' WHERE id=? AND status='open'",t.id).run();continue;}data={round:0,pairs:[],history:[]};}
  else {for(const pair of data.pairs){if(pair.winner)continue;const result=await this.one('SELECT winner FROM results WHERE id=?',pair.room);if(result)pair.winner=result.winner;else {const room=await this.one('SELECT * FROM rooms WHERE id=?',pair.room);if(room?.status==='active'){const rd:RoomData=JSON.parse(room.data);if(this.now-Math.min(...rd.seen)>10000){const present=rd.seen.map((seen,index)=>({seen,index})).filter(p=>this.now-p.seen<=10000);rd.race.status='finished';rd.race.winner=present.length===1?rd.race.cars[present[0].index].id:null;rd.race.reason=rd.race.winner?'Victorie prin deconectare':'Ambii piloți s-au deconectat.';const finished=await this.q("UPDATE rooms SET status='finished',data=?,rev=rev+1 WHERE id=? AND rev=?",JSON.stringify(rd),room.id,room.rev).run();if(finished.meta.changes){await this.settle(room,rd);if(rd.race.winner)pair.winner=rd.race.winner;else pair.eliminated=true;}}}if(room?.status==='finished'&&!JSON.parse(room.data).race.winner)pair.eliminated=true;if(room?.status==='invited'&&this.now-room.created>120000){const players=await this.all('SELECT id,seen FROM players WHERE id IN (?,?) ORDER BY seen DESC,id',pair.a,pair.b);pair.winner=players[0].id;qs.push(this.q("UPDATE rooms SET status='cancelled' WHERE id=? AND status='invited'",room.id));pair.forfeit=true;}}}if(data.pairs.some((p:any)=>!p.winner&&!p.eliminated))continue;ids=data.pairs.map((p:any)=>p.winner).filter(Boolean);data.history.push({round:data.round,pairs:data.pairs});}
  let status='running',winner=null;
  if(ids.length<=1){status=ids.length?'finished':'cancelled';winner=ids[0]||null;data.pairs=[];}
  else {data.round++;data.pairs=[];const season=await this.season();for(let i=0;i<ids.length;i+=2){const a=ids[i],b=ids[i+1];if(!b){data.pairs.push({a,b:null,winner:a,bye:true});continue;}const id=t.id+':'+data.round+':'+i;const pa=await this.one('SELECT * FROM players WHERE id=?',a),pb=await this.one('SELECT * FROM players WHERE id=?',b),rd:RoomData={race:newRace(t.track,[{id:a,name:pa.name,lane:0,tyre:pa.tyre},{id:b,name:pb.name,lane:1,tyre:pb.tyre}]),seen:[this.now,this.now],tick:this.now,paused:false,pauseUntil:0,season:season.id};data.pairs.push({a,b,room:id,winner:null});qs.push(this.q("INSERT OR IGNORE INTO rooms(id,host,guest,status,data,created,tournament) SELECT ?,?,?,'invited',?,?,? WHERE EXISTS(SELECT 1 FROM tournaments WHERE id=? AND rev=?)",id,a,b,JSON.stringify(rd),this.now,t.id,t.id,t.rev));}}
  // The revision predicate prevents two concurrent lobby polls from advancing the bracket twice.
  qs.push(this.q('UPDATE tournaments SET data=?,status=?,winner=?,rev=rev+1 WHERE id=? AND rev=?',JSON.stringify(data),status,winner,t.id,t.rev));await this.db.batch(qs);
 }}
}

