// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
// See examples/d1/db/schema.ts for an opt-in example.
import {sqliteTable,text,integer,real,index} from 'drizzle-orm/sqlite-core';
export const players=sqliteTable('players',{id:text('id').primaryKey(),name:text('name').notNull(),country:text('country').notNull().default('România'),avatar:text('avatar').notNull().default('P'),tyre:text('tyre').notNull().default('medium'),points:integer('points').notNull().default(0),wins:integer('wins').notNull().default(0),losses:integer('losses').notNull().default(0),titles:integer('titles').notNull().default(0),admin:integer('admin').notNull().default(0),seen:integer('seen').notNull(),created:integer('created').notNull()});
export const seasons=sqliteTable('seasons',{id:text('id').primaryKey(),name:text('name').notNull(),active:integer('active').notNull().default(1),winner:text('winner'),created:integer('created').notNull()});
export const rooms=sqliteTable('rooms',{id:text('id').primaryKey(),host:text('host').notNull(),guest:text('guest').notNull(),status:text('status').notNull(),data:text('data').notNull(),rev:integer('rev').notNull().default(0),created:integer('created').notNull(),tournament:text('tournament')},t=>[index('rooms_host_status').on(t.host,t.status),index('rooms_guest_status').on(t.guest,t.status)]);
export const locks=sqliteTable('locks',{player:text('player').primaryKey(),room:text('room').notNull()});
export const results=sqliteTable('results',{id:text('id').primaryKey(),token:text('token').notNull(),winner:text('winner').notNull(),loser:text('loser').notNull(),track:text('track').notNull(),time:real('time').notNull(),season:text('season').notNull(),tournament:text('tournament'),created:integer('created').notNull()},t=>[index('results_season').on(t.season),index('results_winner').on(t.winner)]);
export const records=sqliteTable('records',{id:text('id').primaryKey(),player:text('player').notNull(),track:text('track').notNull(),lap:real('lap').notNull(),total:real('total'),room:text('room').notNull()},t=>[index('records_track_lap').on(t.track,t.lap),index('records_player').on(t.player)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),channel:text('channel').notNull(),sender:text('sender').notNull(),body:text('body').notNull(),created:integer('created').notNull()},t=>[index('messages_channel_created').on(t.channel,t.created)]);
export const tournaments=sqliteTable('tournaments',{id:text('id').primaryKey(),name:text('name').notNull(),track:text('track').notNull(),starts:integer('starts').notNull(),max:integer('max').notNull(),rules:text('rules').notNull(),status:text('status').notNull().default('open'),data:text('data').notNull().default('{}'),rev:integer('rev').notNull().default(0),winner:text('winner'),created:integer('created').notNull()});
export const entrants=sqliteTable('entrants',{id:text('id').primaryKey(),tournament:text('tournament').notNull(),player:text('player').notNull()},t=>[index('entrants_tournament').on(t.tournament)]);
