import {getFirebaseUser} from '@/app/firebase-auth';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {env} from 'cloudflare:workers';
import {GameService} from '@/lib/game-service';
export const dynamic='force-dynamic';
function response(data:unknown,status=200,origin?:string){return Response.json(data,{status,headers:{'Cache-Control':'no-store',...(origin?{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Credentials':'true'}:{})}});}
async function user(req:Request){return (await getFirebaseUser(req))?.userId||(await getChatGPTUser())?.userId||null;}
export async function OPTIONS(req:Request){return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':req.headers.get('origin')||'*','Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'}});}
export async function GET(req:Request){try{const origin=req.headers.get('origin')||undefined;if(!env.DB)return response({error:'Serviciul online se pregătește. Antrenamentul rămâne disponibil.'},503,origin);const s=new GameService(env.DB,await user(req));const u=new URL(req.url);return response(u.searchParams.has('channel')?await s.chat(u.searchParams.get('channel')):await s.lobby(),200,origin);}catch(e:any){return response({error:e.status?e.message:'Serviciul online nu răspunde. Reîncearcă.'},e.status||503,req.headers.get('origin')||undefined);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&& !/^https:\/\/(racechallenge-4d79c\.web\.app|racechallenge-4d79c\.firebaseapp\.com)$/.test(origin))return response({error:'Cerere nepermisă.'},403);if(!env.DB)return response({error:'Serviciul online nu este disponibil.'},503,origin||undefined);const raw=await req.text();if(raw.length>4096)return response({error:'Cerere prea mare.'},413,origin||undefined);let body;try{body=JSON.parse(raw);}catch{return response({error:'Cerere invalidă.'},400,origin||undefined);}const s=new GameService(env.DB,await user(req));switch(body.action){case 'profile':return response(await s.profile(body),200,origin||undefined);case 'challenge':return response(await s.challenge(body),200,origin||undefined);case 'accept':return response(await s.accept(body),200,origin||undefined);case 'decline':return response(await s.decline(body),200,origin||undefined);case 'tick':return response(await s.tick(body),200,origin||undefined);case 'message':return response(await s.message(body),200,origin||undefined);case 'tournament':return response(await s.createTournament(body),200,origin||undefined);case 'join':return response(await s.join(body),200,origin||undefined);case 'season':return response(await s.newSeason(body),200,origin||undefined);default:return response({error:'Acțiune necunoscută.'},400,origin||undefined);}}catch(e:any){return response({error:e.status?e.message:'Acțiunea nu a putut fi salvată. Reîncearcă.'},e.status||503,origin||undefined);}}
